name: Ktab
version: ${project.version}
main: me.krunsh.ktab.KtabPlugin
description: Tablist configurable pour Volkaria
author: krunsh

depend:
  - PlaceholderAPI

softdepend:
  - ServerNPC

commands:
  ktab:
    description: Administration de Ktab
    usage: /ktab <status|reload|preview|debug|refresh|clear|skin>
    permission: ktab.admin

permissions:
  ktab.admin:
    description: Administrer Ktab
    default: op
